### ISSUE TITLE
can permanently clobber built in functions

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#166]
if you type

    Game.background=null;

the Game.background can't be called until you reload the browser session.

try running this and uncommenting/commenting the null line to test

    function new() {
      Game.background(Col.BLACK);
    // Game.background=null;
      Game.background(Col.WHITE);
    }

    function update() {
    }	

should probably reset/reregister all the builtin functions when things are recompiled

**Comment by TerryCavanagh** [comment]
Ok, I changed things so that the entire system is set up again when you reload!
