### ISSUE TITLE
std vs convert

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#191]
convert does a lot of the things that std does - I'd recommend either fully wrapping the needed functions from std (int/float to/from strings, float->int) in convert, or ditching convert. I'd be slightly in favour of using convert, because it sounds nicer :)

**Comment by TerryCavanagh** [comment]
Huh: so, in theory, Convert does *everything* that Std does, or should do. What's missing, exactly?

**Comment by increpare** [comment]
You're right, it's not needed!

The only problem with convert is this one:
https://github.com/increpare/terrylib_online/issues/84
