### ISSUE TITLE
rename Debug.Log to trace?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#208]
what do you think? (it's already defined in hscript, it just goes straight to the console)

**Comment by increpare** [comment]
or how about just log? i dunno. maybe it's fine as is.

**Comment by TerryCavanagh** [comment]
I've added trace as an alternative to Debug.log - it's a basic haxe command that people will expect to work, so it's good to have in there. It does the same thing as Debug.log, but Debug.log is called from lots of terrylibweb functions now - so maybe let's just leave it there, and remove Debug.log from the autocomplete.

**Comment by increpare** [comment]
"Debug.log is called from lots of terrylibweb functions now"

those are all from within haxe though, not haxescript - so you could not expose the Debug class?

**Comment by TerryCavanagh** [comment]
Ok, I removed Debug.log. Some examples are gonna be broken! (actually I'll just search replace and fix those now)
