### ISSUE TITLE
mouse.mousewheel's rest state is -1

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#210]
function new(){
    }

    function update(){
      Debug.log(Mouse.mousewheel);
    }

prints lots of -1s once i stop scrolling. happens in firefox, safari, and chrome.

**Comment by TerryCavanagh** [comment]
Hmm. Have you recompiled? I think this is fixed now!

**Comment by increpare** [comment]
yep, works!

**Comment by increpare** [comment]
it's ok for the values to get very big/small (-300 to 300 ) and take about a second to wind down to 0?

**Comment by TerryCavanagh** [comment]
Cool!

With the big values, I dunno - it seems to be because of a system wide setting for scroll speed. I think I'd rather just have a scrolled up/scrolled down check. Might have another look at this later, so.

**Comment by TerryCavanagh** [comment]
In the sprite editor, when you scroll up and down with the wheel, can you stop in the middle? I.e. There are three brush sizes - can you select the middle one?

**Comment by increpare** [comment]
>In the sprite editor, when you scroll up and down with the wheel, can you stop in the middle?

If I focus really really really hard it's possible. But it's not fun.

**Comment by TerryCavanagh** [comment]
Ok, I'll implement proper functions for it so :D
