### ISSUE TITLE
some Math. things missing?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#218]
Should we have Math.NaN, Math.isNan(), Math.POSITIVE_INFINITY, Math.NEGATIVE_INFINITY (and maybe some others I've missed out on)?

**Comment by increpare** [comment]
also missing: ffloor, fceil

(fround is present, though)

**Comment by TerryCavanagh** [comment]
Oh, I dunno! I've never used them, but I guess it couldn't hurt?

**Comment by increpare** [comment]
they should be in the standard library, according to http://api.haxe.org/Math.html
spooky

**Comment by increpare** [comment]
(they're not needed though I think, just a case of getting the documentation right :) ).

**Comment by increpare** [comment]
remo
