### ISSUE TITLE
createimage/drawtoimage working?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#221]
This doesn't do what I think it should do. What am I doing wrong?

    Gfx.createimage("pic",30,30);
    Gfx.drawtoimage("pic");
    Gfx.fillbox(10,10,10,10,Col.RED);
    Gfx.drawtoscreen();

    function update(){
      Gfx.drawimage(0,0,"pic");
      Text.display(0,0,"hey");
    }

**Comment by TerryCavanagh** [comment]
Something weird is happening here, because this *should* be fixed. Also, the screenshot you took of the sprite editor seems to indicate that you're a revision or two behind me, somehow. Maybe you need to recompile webthing.js on your end?

**Comment by increpare** [comment]
oh, it works now! yay!

**Comment by increpare** [comment]
(I had to rebuild, yip)

**Comment by TerryCavanagh** [comment]
Yay!
