### ISSUE TITLE
delaypressed - waits a bit too long?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#227]
internally, do you need to do a -1 somewhere?

    function update(){
      //if you hold a, should trigger once every 30 frames
      if (Input.delaypressed(Key.A,1)){
        Debug.log(Game.time);
      }
    }

produces

line 4 : 8
line 4 : 10
line 4 : 12
line 4 : 14
line 4 : 16
line 4 : 18
line 4 : 20
line 4 : 22
line 4 : 24
line 4 : 26

**Comment by TerryCavanagh** [comment]
Oh, whoops!
