### ISSUE TITLE
this is flashing the whole screen red for one frame - what am I doing wrong?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#228]
Gfx.createimage("pic",10,10);
    Gfx.drawtoimage("pic");
    Gfx.clearscreen(Col.RED);
    Gfx.drawtoscreen();

    function update(){
      Gfx.drawimage(0,0,"pic");
    }

**Comment by TerryCavanagh** [comment]
Oh, this is because clearscreen is still only applying to the backbuffer, instead of the current surface. Fixing that now!

**Comment by increpare** [comment]
yay! thanks!

**Comment by TerryCavanagh** [comment]
Hmm, you'll have to recompile for this one too, I guess. Why is that? PuzzleScript\terrylibweb\bin\html5\bin\webthing.js isn't in the gitignore (although the old PuzzleScript/webthing.js is)

**Comment by increpare** [comment]
hmm. i don't know.

**Comment by increpare** [comment]
are you sure the code example above works for you now? it's not working for me

**Comment by increpare** [comment]
(now i just get a black screen)

**Comment by TerryCavanagh** [comment]
Oh! Sorry, try again!

**Comment by increpare** [comment]
👍🏽
