### ISSUE TITLE
Text.getinput is something to do with Text.input, right?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#233]
So I can ignore it for now

https://github.com/increpare/terrylib_online/issues/46

(if we ditch getinput/input as they are now, I'd happily have a function that returns, as a string, whatever keys were pressed that frame (empty string if nothing));

**Comment by TerryCavanagh** [comment]
I really should figure out what's causing this - Text.input is a super nice way to let people type stuff in easily, when it works... (sprite editor for now!)
