### ISSUE TITLE
Rethink BASE512

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/terrylib_online#251]
Here's an example of the new function, Gfx.loadimagestring();

``` haxe
function new(){
  Gfx.loadimagestring("test", "ɎAATÅЦ‰плӯГŢHɏADɏɏAŽɏɌfɏɏɀɈŽfпҗɀɏɌķЏɏӓɈŽɏɏɏɏɏɏɏɏADɉɀAäfӐHɀķɏɎAɏɏҐAɏӐA");
}

function update(){
  Gfx.clearscreen(Col.NIGHTBLUE);
  Gfx.drawimage(Gfx.screenwidthmid-32,Gfx.screenheightmid-32,"test", {scale:4});
}
```

The BASE512 string works great in flashdevelop, in codemirror, in lots of places - but in notepad, for example, the string turns into this:

```
Gfx.loadimagestring("test", "?AATÅ?‰????TH?AD??AŽ??f????Žf?????k????Ž????????AD??Aäf?H?k??A???A??A");
```

Which sorta destroys the point of it. Probably better off using a copy and paste safe base 128 instead.

**Comment by TerryCavanagh** [comment]
Cool, BASE128 it is. Here's the new BASE128 string, tested copy and paste safe.

``` haxe
var BASE128:String = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ÄäÀàÁáÂâÃãÅåœÇçÐðÈèÉéÊêËëÌìÍíÎîÏïÑñÖöÒòÓóÔôÕõØøßŠšÞþÜüÙùÚúÛûÝýŸÿžŽ";
```

And an example image:

``` haxe
Gfx.loadimagestring("test", "7ÀAAFÛçzÉüÂüNLòAqÀKèCêAËËäùvÿrŽqŽÀ", Col.TRANSPARENT);
```

**Comment by increpare** [comment]
Looks grand.  

1 - I guess it's not worth looking to replace the numbers with other characters so you can do rle on top? (i see you're missing the greek alphabet - notepad doesn't support that?)
2 - Consider in your function to strip spaces and newlines and tabs and stuff from it - that allows people to space long things out neatly over multiple lines. (Mainly useful for keeping the music examples on screen - http://ded.increpare.com/~locus/terrylib_online/PuzzleScript/Documentation/Music.html )

**Comment by TerryCavanagh** [comment]
1: I did some messing around with RLE as well, but it was pretty hard to find examples where it wasn't just making things worse for this.

2: Good call! Done!

**Comment by TerryCavanagh** [comment]
Ok, this BASE128 string might be safe for notepad, but it's not safe for firefox's text prompt. Reopening and rethinking.

**Comment by increpare** [comment]
What happens when you try paste?

**Comment by TerryCavanagh** [comment]
The prompt text box contains question marks instead of the proper symbols :(
