### ISSUE TITLE
think about if some anim/tilemap functions are necessary

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#26]
["Gfx.grabtilefromscreen","(tilenumber, screen x, screen y)"],
["Gfx.grabtilefromimage","(tilenumber, imagename, image x, image y)"],
["Gfx.grabimagefromscreen","(imagename, screen x, screen y)"],
["Gfx.grabimagefromimage","(imagename, sourceimagename, image x, image y)"],
["Gfx.defineanimation","(animname, tileset, start frame, end frame, delay)"],
["Gfx.drawanimation","(x, y, animationname, optional parameters)"],
["Gfx.stopanimation","(animation name)"],

**Comment by increpare** [comment]
don't forget to remove entries from editor.js as well if you do

**Comment by TerryCavanagh** [comment]
Ok, I scrapped the tile and animation functions - about 20 or so in total. Kept the image functions, which can still be used for interesting stuff even if you can't load images into them.
