### ISSUE TITLE
why are .RGB and .HSL capitalized?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#262]

**Comment by increpare** [comment]
actually, this isn't important really :P

**Comment by TerryCavanagh** [comment]
no, good point! It's inconsistant, and I'm only doing it because of Allegro habits that I shouldn't pass down. Let's change it!

**Comment by increpare** [comment]
I'll change it :)

**Comment by TerryCavanagh** [comment]
It seems like there are a bunch of places this needs to be changed: the library itself, the documentation, and all the current examples. I'll do the library now, and we can do the rest later.
