### ISSUE TITLE
update needs to be after variable delclarations?

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/terrylib_online#63]
Noticed a weird bug due to this. Consider doing som preprocessing to move update function to the end before parsing. (Could also use this to catch some basic bugs before running the parser and giving more useful error messages, catching text.display vs Text.display eg)

**Comment by increpare** [comment]
saw this as well, yip. like writing c innit :)

**Comment by increpare** [comment]
oh right that's the error with the first demo.  I updated error logging which makes it easier to see

it says this now :
"RUNTIME ERROR: EUnknownVariable i"

**Comment by increpare** [comment]
wait, no, no it's not. ignore me

**Comment by TerryCavanagh** [comment]
Just tried the thing of having a secret, hidden update function that called the real one, but that didn't work. On further investigation, this is kinda bigger than I thought - here's an example:

``` haxe
function new() {
  testvar = "ok!";
}

var testvar:String = "not ok :(";

function update() {
  Debug.log(testvar);
}
```

**Comment by increpare** [comment]
are we just closing this now?

the idea is that var creates local variables, and variables declared without var are global (and somehow var on the top level isn't as global as it gets - it's not documented very well - could log a bug report with hscript?)

**Comment by increpare** [comment]
closing this, it's covered by  #187
