### ISSUE TITLE
gfx screwed up (no repro, just a report/screenshot)

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#64]
this happened somehow. no idea how to repro

<img width="586" alt="screen shot 2015-08-29 at 01 15 56" src="https://cloud.githubusercontent.com/assets/465632/9559457/a24f8c84-4deb-11e5-94ba-81a4a8250f0b.png">

**Comment by increpare** [comment]
Oh, I have a repro

load

editor.html?hack=48c994b0739d2beef698

run it, notice it's cool

uncomment line 271
//    		 Gfx.fillbox(x,y,cellWidth*l-1,cellHeight-1,col);

run. notice it's fucked. hit stop. notice it looks like the above.

**Comment by increpare** [comment]
ah, it's to do with passing undefined to fillbox. Here we go

run and stop the following to repro

function update() {
  Gfx.fillbox();
}

:D

**Comment by TerryCavanagh** [comment]
Fixed!
